name: Publish Any Commit
on:
  # Temporarily disabled - uncomment to re-enable
  # pull_request:
  # push:
  #   branches:
  #     - '**'
  #   tags:
  #     - '!**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm & install
        uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 22

      - name: Build
        run: pnpm build

      - run: pnpm dlx pkg-pr-new publish --bin
